// Code generated by protoc-gen-go.
// source: test.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	SearchRequest
	SearchResponse
	Result
	AccountInfo
	GetAccountInfoParams
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchRequest struct {
	Query         string `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	PageNumber    int32  `protobuf:"varint,2,opt,name=page_number,json=pageNumber" json:"page_number,omitempty"`
	ResultPerPage int32  `protobuf:"varint,3,opt,name=result_per_page,json=resultPerPage" json:"result_per_page,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *SearchRequest) GetResultPerPage() int32 {
	if m != nil {
		return m.ResultPerPage
	}
	return 0
}

type SearchResponse struct {
	Result []*Result `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SearchResponse) GetResult() []*Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type Result struct {
	Url      string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Title    string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Snippets string `protobuf:"bytes,3,opt,name=snippets" json:"snippets,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Result) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Result) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Result) GetSnippets() string {
	if m != nil {
		return m.Snippets
	}
	return ""
}

type AccountInfo struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *AccountInfo) Reset()                    { *m = AccountInfo{} }
func (m *AccountInfo) String() string            { return proto.CompactTextString(m) }
func (*AccountInfo) ProtoMessage()               {}
func (*AccountInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AccountInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetAccountInfoParams struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetAccountInfoParams) Reset()                    { *m = GetAccountInfoParams{} }
func (m *GetAccountInfoParams) String() string            { return proto.CompactTextString(m) }
func (*GetAccountInfoParams) ProtoMessage()               {}
func (*GetAccountInfoParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetAccountInfoParams) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*SearchRequest)(nil), "main.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "main.SearchResponse")
	proto.RegisterType((*Result)(nil), "main.Result")
	proto.RegisterType((*AccountInfo)(nil), "main.AccountInfo")
	proto.RegisterType((*GetAccountInfoParams)(nil), "main.GetAccountInfoParams")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SearchService service

type SearchServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	SearchAlt(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type searchServiceClient struct {
	cc *grpc.ClientConn
}

func NewSearchServiceClient(cc *grpc.ClientConn) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := grpc.Invoke(ctx, "/main.SearchService/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) SearchAlt(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := grpc.Invoke(ctx, "/main.SearchService/SearchAlt", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SearchService service

type SearchServiceServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	SearchAlt(context.Context, *SearchRequest) (*SearchResponse, error)
}

func RegisterSearchServiceServer(s *grpc.Server, srv SearchServiceServer) {
	s.RegisterService(&_SearchService_serviceDesc, srv)
}

func _SearchService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.SearchService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_SearchAlt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).SearchAlt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.SearchService/SearchAlt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).SearchAlt(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _SearchService_Search_Handler,
		},
		{
			MethodName: "SearchAlt",
			Handler:    _SearchService_SearchAlt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}

// Client API for AccountService service

type AccountServiceClient interface {
	GetAccountInfo(ctx context.Context, in *GetAccountInfoParams, opts ...grpc.CallOption) (*AccountInfo, error)
	Search(ctx context.Context, in *GetAccountInfoParams, opts ...grpc.CallOption) (*SearchResponse, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) GetAccountInfo(ctx context.Context, in *GetAccountInfoParams, opts ...grpc.CallOption) (*AccountInfo, error) {
	out := new(AccountInfo)
	err := grpc.Invoke(ctx, "/main.AccountService/GetAccountInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Search(ctx context.Context, in *GetAccountInfoParams, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := grpc.Invoke(ctx, "/main.AccountService/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AccountService service

type AccountServiceServer interface {
	GetAccountInfo(context.Context, *GetAccountInfoParams) (*AccountInfo, error)
	Search(context.Context, *GetAccountInfoParams) (*SearchResponse, error)
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_GetAccountInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountInfoParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAccountInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.AccountService/GetAccountInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAccountInfo(ctx, req.(*GetAccountInfoParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountInfoParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.AccountService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Search(ctx, req.(*GetAccountInfoParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccountInfo",
			Handler:    _AccountService_GetAccountInfo_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _AccountService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}

func init() { proto.RegisterFile("test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x49, 0xff, 0x04, 0x33, 0xb5, 0x51, 0xc7, 0x1e, 0x42, 0x2e, 0xd6, 0x20, 0xa5, 0xa7,
	0x1e, 0x5a, 0xe8, 0xc1, 0x8b, 0xf4, 0x24, 0x82, 0x48, 0xd9, 0x3e, 0x40, 0xd9, 0xa6, 0x63, 0x0d,
	0x24, 0x9b, 0x74, 0x77, 0x23, 0x08, 0xbe, 0x82, 0xef, 0x2c, 0xd9, 0x4d, 0x4b, 0x03, 0x45, 0xf0,
	0x36, 0xf3, 0xcd, 0x37, 0x3b, 0xbf, 0x19, 0x16, 0x40, 0x93, 0xd2, 0x93, 0x42, 0xe6, 0x3a, 0xc7,
	0x4e, 0xc6, 0x13, 0x11, 0x09, 0xe8, 0xaf, 0x88, 0xcb, 0xf8, 0x83, 0xd1, 0xbe, 0x24, 0xa5, 0x71,
	0x00, 0xdd, 0x7d, 0x49, 0xf2, 0x2b, 0x70, 0x86, 0xce, 0xd8, 0x63, 0x36, 0xc1, 0x3b, 0xe8, 0x15,
	0x7c, 0x47, 0x6b, 0x51, 0x66, 0x1b, 0x92, 0x41, 0x6b, 0xe8, 0x8c, 0xbb, 0x0c, 0x2a, 0xe9, 0xcd,
	0x28, 0x38, 0x82, 0x2b, 0x49, 0xaa, 0x4c, 0xf5, 0xba, 0x20, 0xb9, 0xae, 0x0a, 0x41, 0xdb, 0x98,
	0xfa, 0x56, 0x5e, 0x92, 0x5c, 0xf2, 0x1d, 0x45, 0x73, 0xf0, 0x0f, 0xf3, 0x54, 0x91, 0x0b, 0x45,
	0xf8, 0x00, 0xae, 0xb5, 0x04, 0xce, 0xb0, 0x3d, 0xee, 0x4d, 0x2f, 0x27, 0x15, 0xd8, 0x84, 0x19,
	0x8d, 0xd5, 0xb5, 0xe8, 0x15, 0x5c, 0xab, 0xe0, 0x35, 0xb4, 0x4b, 0x99, 0xd6, 0x78, 0x55, 0x58,
	0x21, 0xeb, 0x44, 0xa7, 0x64, 0xb0, 0x3c, 0x66, 0x13, 0x0c, 0xe1, 0x42, 0x89, 0xa4, 0x28, 0x48,
	0x2b, 0x83, 0xe2, 0xb1, 0x63, 0x1e, 0xdd, 0x43, 0x6f, 0x11, 0xc7, 0x79, 0x29, 0xf4, 0x8b, 0x78,
	0xcf, 0x11, 0xa1, 0x23, 0x78, 0x46, 0xf5, 0x9b, 0x26, 0x8e, 0x46, 0x30, 0x78, 0x26, 0x7d, 0xe2,
	0x5a, 0x72, 0xc9, 0x33, 0x85, 0x3e, 0xb4, 0x92, 0x6d, 0xed, 0x6c, 0x25, 0xdb, 0xe9, 0xf7, 0xe1,
	0x80, 0x2b, 0x92, 0x9f, 0x49, 0x4c, 0x38, 0x03, 0xd7, 0x0a, 0x78, 0x6b, 0x37, 0x69, 0xdc, 0x37,
	0x1c, 0x34, 0xc5, 0xfa, 0x08, 0x73, 0xf0, 0xac, 0xb2, 0x48, 0xf5, 0x3f, 0xfa, 0xa6, 0x3f, 0x0e,
	0xf8, 0x35, 0xe3, 0x61, 0xfe, 0x13, 0xf8, 0x4d, 0x70, 0x0c, 0x6d, 0xeb, 0xb9, 0x75, 0xc2, 0x1b,
	0x5b, 0x3b, 0xb5, 0x3f, 0x1e, 0x17, 0xf8, 0xab, 0xf1, 0x2c, 0xcf, 0xc6, 0x35, 0x7f, 0x6b, 0xf6,
	0x1b, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x28, 0xd4, 0xcd, 0x69, 0x02, 0x00, 0x00,
}
